/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 hand5.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import Hand5 from './hand5.glb'

export default function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF('/hand5.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" rotation={[Math.PI / 2, 0, 0]} />
        <group name="Empty001" position={[-0.466, -1.047, 0]} rotation={[Math.PI, 0, Math.PI / 4]} scale={[-0.193, -0.175, -0.22]} />
        <group name="Armature001" rotation={[0, 0, -0.778]} scale={[1, 1.07, 1]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone002} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone008} />
          <primitive object={nodes.Bone011} />
          <primitive object={nodes.Bone014} />
          <skinnedMesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials.Material} skeleton={nodes.Cylinder006.skeleton} />
        </group>
        <group name="Armature">
          <primitive object={nodes.Bone_1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(Hand5);
